### ISSUE TITLE
Issues openning item when used on iOS 17

### ISSUE THREAD

**Issue by kristian-palovic-work** [yaminncco/vue-sidebar-menu#268]
When tested on the other devices, it works flawlessly. But in Safari (tested on upper mentioned version of iOS), it requires always click anywhere within the `<SidebarMenu>` component first time, and only on the second click it interacts with the listed items.

**Comment by EdwardSimmons** [comment]
I'm also experiencing issues on iOS + Safari (although I'm on iOS 15, so possibly not identical). As mentioned above by Kristián, I have to tap twice on the side drawer for any navigation to occur.

When I tap on a menu item while the menu is collapsed, the expanded sidebar item fails to transition back into the collapsed state (see below).

<img src="https://github.com/yaminncco/vue-sidebar-menu/assets/67064026/479ff7b6-1e68-4483-9c0e-024c308449d1" height="500">

Interacting with the menu while it's expanded also requires two taps to navigate.

**Comment by peter-tell** [comment]
I'm also experiencing this.

**Comment by yaminncco** [comment]
Can someone confirm if the issue still persists in the latest version?

**Comment by kristian-palovic-work** [comment]
@yaminncco tested on IPhone 12 iOS 17.2., 14 and It seems like it was fixed :slightly_smiling_face: . But when testing it on IPhone 11 iOS 13, the top level dropdown has to be clicked twice (first time).

(Sorry for missing cursor)

![ezgif-7-4f21719f5f](https://github.com/yaminncco/vue-sidebar-menu/assets/97879345/62e2a4f3-6302-4b72-a741-109502ae31bf)

**Comment by EdwardSimmons** [comment]
Hi @yaminncco, apologies for the delay in testing. 

The two-taps-to-navigate issue seems to be resolved, thank you! I also tested on the latest iOS (17.2.1), so I can't speak for older versions sorry.

I'm still experiencing the bug where expanded menu items fail to collapse after selecting them though :(

https://github.com/yaminncco/vue-sidebar-menu/assets/67064026/4b49a668-3c4e-475c-8415-dbc994b715ff

**Comment by LwtsdeFrisch** [comment]
This also happens to me in Google Chrome, especially when moving the cursor out the browser window and over the sidebar. It stays open and i can only close it when switching to another icon.
